# Generated by Django 5.1.6 on 2025-03-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
